# Generated by Django 6.0.2 on 2026-03-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_servicerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
