# Generated by Django 6.0.2 on 2026-03-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_serviceorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
